Resources:
  WebsiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - ${self:custom.domain.${self:custom.stage}}
          - www.${self:custom.domain.${self:custom.stage}}
        Origins:
          - DomainName: atlauncher-website-${self:custom.stage}.s3.amazonaws.com
            Id: WebsiteFilesBucket
            S3OriginConfig:
              OriginAccessIdentity: { "Fn::Join" : ["", ["origin-access-identity/cloudfront/", { Ref: WebsiteOriginAccessIdentity } ] ]  }
        Enabled: 'true'
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: 'PriceClass_100'
        HttpVersion: 'http2'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: WebsiteFilesBucket
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: all
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: ${self:custom.acmArn.${self:custom.stage}}
          SslSupportMethod: 'sni-only'
          MinimumProtocolVersion: TLSv1.1_2016
        Logging:
          Bucket:
            Fn::GetAtt:
              - CloudfrontLogsBucket
              - DomainName

Outputs:
  WebsiteCloudFrontDistributionDomainName:
    Value:
      'Fn::GetAtt': [WebsiteCloudFrontDistribution, DomainName]
